server:
  port: 8086
logging:
#  config: classpath:logback.xml
  level:
    com.nucarf.app.ntocc: debug
    org.springframework: debug
    org.hibernate: error
spring:
  datasource:
    url: jdbc:mysql://192.168.0.39:3307/saas_dev?useSSL=false
    username: java_ci
    password: LasfdMsafD34N677uNssOSK
    driver-class-name: com.mysql.jdbc.Driver
